version: '3.8'
services:
  app:
    container_name: tzonetracker
    image: ipajudd/tzonetracker:latest
    volumes:
      - .:/app
    environment:
      - DEBUG_WEBHOOK=${DEBUG_WEBHOOK}
      - WEBHOOK1=${WEBHOOK1}
      - WEBHOOK2=${WEBHOOK2}
      - WEBHOOK3=${WEBHOOK3}
      - WEBHOOK4=${WEBHOOK4}
      - WEBHOOK5=${WEBHOOK5}
      - WEBHOOK6=${WEBHOOK6}
      - WEBHOOK7=${WEBHOOK7}
      - WEBHOOK8=${WEBHOOK8}
      - WEBHOOK9=${WEBHOOK9}
      - WEBHOOK10=${WEBHOOK10}
    restart: unless-stopped
